class Config:
    SQLALCHEMY_DATABASE_URI = 'sqlite:///database.db'
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    API_KEY = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1ZWQwMzQ0ZDQ3NWUzNTE1NzNkZjU3OGYiLCJpYXQiOjE3MTk3Nzk4NzksInJvbGUiOiJhZG1pbiJ9.POhPLDodqgLoc-hCLJtFS75l2wlXbOricSHOpLoHFps'
    NICTLA_APP_ID = 'nixtla-tok-YBifTaKnrMIy8P97ruMsDM6H72UHu095s6S3EkQPddsPSMQBUizhXKrmDpWVgqk0O9iOtqzid4QPuNPz'